title: Spectrogram Labeling
type: community
group: Audio/Speech Processing
image: /static/templates/spectrogram.png
details: <h1>Provide transcript for the audio</h1>
config: |
  <View>
     <Labels name="labels" toName="spec">
      <Label value="Mopsfledermaus" />
      <Label value="Mückenfledermaus" />
    </Labels>
  
    <Spectrogram name="spec" value="$audio" />
  
  </View>

